networks:
  piko:
    name: "piko"
services:
  influxdb:
    image: "influxdb:2.0-alpine"
    networks:
      - piko
    expose:
      - "8086"
    ports:
      - "8086:8086"
    environment:
      - TZ=Europe/Berlin
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - $PWD/.influxdb:/var/lib/influxdb2
      - $PWD/config.yml:/etc/influxdb2/config.yml
  telegraf:
    image: "telegraf:1.17-alpine"
    depends_on:
      - influxdb
    networks:
      - piko
    environment:
      - TZ=Europe/Berlin
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
