version: '3'
networks:
  influx-net:
    name: "influx-net"
services:
  influxdb:
    image: "influxdb:2.6-alpine"
    networks:
      - influx-net
    ports:
      - "8086:8086"
    environment:
      - TZ=Europe/Berlin
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - $PWD/.influxdb:/var/lib/influxdb2:rw
      - $PWD/config.yaml:/etc/influxdb2/config.yaml
  telegraf:
    image: "telegraf:1.25-alpine"
    depends_on:
      - influxdb
    networks:
      - influx-net
    environment:
      - TZ=Europe/Berlin
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
