networks:
  piko:
    name: "piko"
services:
  influxdb:
    image: "influxdb:2.0-alpine"
    networks:
      - piko
    expose:
      - "8086"
    ports:
      - "8086:8086"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - $PWD/.influxdb:/root/.influxdbv2
      - $PWD/config.yml:/etc/influxdb2/config.yml
  telegraf:
    image: "telegraf:1.17-alpine"
    depends_on:
      - influxdb
    networks:
      - piko
    environment:
      - TZ=Europe/Berlin
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    volumes:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
